# Generated by Django 4.1 on 2022-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'AboutBg',
                'verbose_name_plural': 'AboutBgs',
            },
        ),
        migrations.CreateModel(
            name='AboutDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'AboutDesigner',
                'verbose_name_plural': 'AboutDesigners',
            },
        ),
        migrations.CreateModel(
            name='Blog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name2', models.CharField(max_length=120, verbose_name='name2')),
                ('name3', models.CharField(max_length=120, verbose_name='name2')),
                ('name4', models.CharField(max_length=120, verbose_name='name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'Blog1',
                'verbose_name_plural': 'Blog1s',
            },
        ),
        migrations.CreateModel(
            name='Blog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name2', models.CharField(max_length=120, verbose_name='name2')),
                ('name3', models.CharField(max_length=120, verbose_name='name2')),
                ('name4', models.CharField(max_length=120, verbose_name='name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'Blog2',
                'verbose_name_plural': 'Blog2s',
            },
        ),
        migrations.CreateModel(
            name='IndexAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'IndexAbout',
                'verbose_name_plural': 'IndexAbouts',
            },
        ),
        migrations.CreateModel(
            name='IndexBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('about', models.TextField(verbose_name='about')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'IndexBest',
                'verbose_name_plural': 'IndexBests',
            },
        ),
        migrations.CreateModel(
            name='IndexBg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'IndexBg',
                'verbose_name_plural': 'IndexBgs',
            },
        ),
        migrations.CreateModel(
            name='IndexBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name2', models.CharField(max_length=120, verbose_name='name2')),
                ('name3', models.CharField(max_length=120, verbose_name='name2')),
                ('name4', models.CharField(max_length=120, verbose_name='name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'IndexBlog',
                'verbose_name_plural': 'IndexBlogs',
            },
        ),
        migrations.CreateModel(
            name='IndexDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.TextField(verbose_name='about')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': 'IndexDesigner',
                'verbose_name_plural': 'IndexDesigners',
            },
        ),
        migrations.CreateModel(
            name='IndexDream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
                ('img2', models.ImageField(upload_to='media', verbose_name='img2')),
                ('img3', models.ImageField(upload_to='media', verbose_name='img3')),
                ('img4', models.ImageField(upload_to='media', verbose_name='img4')),
            ],
            options={
                'verbose_name': 'IndexDream',
                'verbose_name_plural': 'IndexDreams',
            },
        ),
        migrations.CreateModel(
            name='IndexLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
            ],
            options={
                'verbose_name': 'IndexLot',
                'verbose_name_plural': 'IndexLots',
            },
        ),
        migrations.CreateModel(
            name='IndexLot2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
                ('inte', models.ImageField(upload_to='', verbose_name='int')),
            ],
            options={
                'verbose_name': 'IndexLot2t',
                'verbose_name_plural': 'IndexLot2s',
            },
        ),
        migrations.CreateModel(
            name='IndexLot3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
                ('inte', models.IntegerField(verbose_name='int')),
            ],
            options={
                'verbose_name': 'IndexLot3',
                'verbose_name_plural': 'IndexLot3s',
            },
        ),
        migrations.CreateModel(
            name='IndexSlayd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': ' IndexSlayd',
                'verbose_name_plural': ' IndexSlayds',
            },
        ),
    ]
