# Generated by Django 4.0.6 on 2022-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlot2',
            name='inte',
            field=models.IntegerField(verbose_name='int'),
        ),
    ]
