# Generated by Django 4.0.6 on 2022-08-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_indexlot2_inte'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=40, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
            options={
                'verbose_name': ' IndexTrend',
                'verbose_name_plural': ' IndexTrends',
            },
        ),
    ]
