# Generated by Django 4.0.6 on 2022-08-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_indextrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdesigner',
            name='about',
            field=models.TextField(default=1, verbose_name='about'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexdesigner',
            name='name2',
            field=models.CharField(max_length=40, verbose_name='name2'),
        ),
    ]
