# Generated by Django 4.0.6 on 2022-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_indexdesigner_about_alter_indexdesigner_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexblog',
            name='img2',
            field=models.ImageField(default=1, upload_to='media', verbose_name='img2'),
            preserve_default=False,
        ),
    ]
