# Generated by Django 4.0.6 on 2022-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_indexblog_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexblog',
            name='name5',
            field=models.CharField(default=1, max_length=120, verbose_name='name5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexblog',
            name='name3',
            field=models.CharField(max_length=120, verbose_name='name3'),
        ),
        migrations.AlterField(
            model_name='indexblog',
            name='name4',
            field=models.CharField(max_length=120, verbose_name='name4'),
        ),
    ]
