# Generated by Django 4.0.6 on 2022-08-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_indexblog_name5_alter_indexblog_name3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='img2',
            field=models.ImageField(default=1, upload_to='media', verbose_name='img2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog2',
            name='img2',
            field=models.ImageField(default=1, upload_to='media', verbose_name='img2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog1',
            name='name3',
            field=models.CharField(max_length=120, verbose_name='name3'),
        ),
        migrations.AlterField(
            model_name='blog1',
            name='name4',
            field=models.CharField(max_length=120, verbose_name='name4'),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='name3',
            field=models.CharField(max_length=120, verbose_name='name3'),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='name4',
            field=models.CharField(max_length=120, verbose_name='name4'),
        ),
    ]
