# Generated by Django 4.0.6 on 2022-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog1_img2_blog2_img2_alter_blog1_name3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='name5',
            field=models.CharField(default=1, max_length=120, verbose_name='name5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog2',
            name='name5',
            field=models.CharField(default=1, max_length=120, verbose_name='name5'),
            preserve_default=False,
        ),
    ]
