# Generated by Django 4.0.6 on 2022-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blog1_name5_blog2_name5'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutbg',
            name='about2',
            field=models.TextField(null=True, verbose_name='about2'),
        ),
        migrations.AddField(
            model_name='indexabout',
            name='about2',
            field=models.TextField(null=True, verbose_name='about2'),
        ),
    ]
